### ISSUE TITLE
Daily additional MP information update has a lot of problems

### ISSUE THREAD

**Issue by henare** [openaustralia/openaustralia#603]
I think this means that more info links and voting information is out of date or missing.

Here's the log from yesterday's run:

```
WARNING: Nokogiri was built against LibXML version 2.7.6, but has dynamically loaded 2.7.8
[DEPRECATION] requiring "RMagick" is deprecated. Use "rmagick" instead
Reading member data...
Web pages, social media URLs and email from APH (via Morph)...
Election results 2007 (from the abc.net.au) ...
Election results 2010 (from the abc.net.au) ...
Election results 2013 (from the abc.net.au)...
Q&A Links...
ERROR: Invalid url http://www.abc.net.au/tv/qanda/mp-profiles/dobe.htm for division dobell
ERROR: Invalid url http://www.abc.net.au/tv/qanda/mp-profiles/lalo.htm for division lalor
ERROR: Invalid url http://www.abc.net.au/tv/qanda/mp-profiles/pert.htm for division perth
ERROR: Invalid url http://www.abc.net.au/tv/qanda/mp-profiles/farr.htm for division farrer
ERROR: Invalid url http://www.abc.net.au/tv/qanda/mp-profiles/ksmi.htm for division kingsford smith
ERROR: Invalid url http://www.abc.net.au/tv/qanda/mp-profiles/hoth.htm for division hotham
ERROR: Invalid url http://www.abc.net.au/tv/qanda/mp-profiles/wrig.htm for division wright
ERROR: Invalid url http://www.abc.net.au/tv/qanda/mp-profiles/ling.htm for division lingiari
ERROR: Invalid url http://www.abc.net.au/tv/qanda/mp-profiles/hasl.htm for division hasluck
ERROR: Invalid url http://www.abc.net.au/tv/qanda/mp-profiles/higg.htm for division higgins
ERROR: Invalid url http://www.abc.net.au/tv/qanda/mp-profiles/dick.htm for division dickson
ERROR: Invalid url http://www.abc.net.au/tv/qanda/mp-profiles/mcma.htm for division mcmahon
ERROR: Invalid url http://www.abc.net.au/tv/qanda/mp-profiles/bran.htm for division brand
ERROR: Invalid url http://www.abc.net.au/tv/qanda/mp-profiles/sydn.htm for division sydney
ERROR: Invalid url http://www.abc.net.au/tv/qanda/mp-profiles/robe.htm for division robertson
ERROR: Invalid url http://www.abc.net.au/tv/qanda/mp-profiles/fras.htm for division fraser
ERROR: Invalid url http://www.abc.net.au/tv/qanda/mp-profiles/mitc.htm for division mitchell
ERROR: Invalid url http://www.abc.net.au/tv/qanda/mp-profiles/mack.htm for division mackellar
ERROR: Invalid url http://www.abc.net.au/tv/qanda/mp-profiles/maki.htm for division makin
ERROR: Invalid url http://www.abc.net.au/tv/qanda/mp-profiles/herb.htm for division herbert
ERROR: Invalid url http://www.abc.net.au/tv/qanda/mp-profiles/hink.htm for division hinkler
ERROR: Invalid url http://www.abc.net.au/tv/qanda/mp-profiles/swan.htm for division swan
ERROR: Invalid url http://www.abc.net.au/tv/qanda/mp-profiles/mayo.htm for division mayo
ERROR: Invalid url http://www.abc.net.au/tv/qanda/mp-profiles/long.htm for division longman
ERROR: Invalid url http://www.abc.net.au/tv/qanda/mp-profiles/oxle.htm for division oxley
ERROR: Invalid url http://www.abc.net.au/tv/qanda/mp-profiles/cala.htm for division calare
ERROR: Invalid url http://www.abc.net.au/tv/qanda/mp-profiles/deak.htm for division deakin
ERROR: Invalid url http://www.abc.net.au/tv/qanda/mp-profiles/stur.htm for division sturt
ERROR: Invalid url http://www.abc.net.au/tv/qanda/mp-profiles/solo.htm for division solomon
ERROR: Invalid url http://www.abc.net.au/tv/qanda/mp-profiles/cann.htm for division canning
ERROR: Invalid url http://www.abc.net.au/tv/qanda/mp-profiles/capr.htm for division capricornia
ERROR: Invalid url http://www.abc.net.au/tv/qanda/mp-profiles/rive.htm for division riverina
ERROR: Invalid url http://www.abc.net.au/tv/qanda/mp-profiles/mara.htm for division maranoa
ERROR: Invalid url http://www.abc.net.au/tv/qanda/mp-profiles/deni.htm for division denison
ERROR: Invalid url http://www.abc.net.au/tv/qanda/mp-profiles/cora.htm for division corangamite
ERROR: Invalid url http://www.abc.net.au/tv/qanda/mp-profiles/ltro.htm for division la trobe
ERROR: Invalid url http://www.abc.net.au/tv/qanda/mp-profiles/petr.htm for division petrie
ERROR: Invalid url http://www.abc.net.au/tv/qanda/mp-profiles/gray.htm for division grayndler
ERROR: Invalid url http://www.abc.net.au/tv/qanda/mp-profiles/stir.htm for division stirling
ERROR: Invalid url http://www.abc.net.au/tv/qanda/mp-profiles/moor.htm for division moore
ERROR: Invalid url http://www.abc.net.au/tv/qanda/mp-profiles/hugh.htm for division hughes
ERROR: Invalid url http://www.abc.net.au/tv/qanda/mp-profiles/jaga.htm for division jagajaga
ERROR: Invalid url http://www.abc.net.au/tv/qanda/mp-profiles/gree.htm for division greenway
ERROR: Invalid url http://www.abc.net.au/tv/qanda/mp-profiles/hume.htm for division hume
ERROR: Invalid url http://www.abc.net.au/tv/qanda/mp-profiles/chis.htm for division chisholm
ERROR: Invalid url http://www.abc.net.au/tv/qanda/mp-profiles/forr.htm for division forrest
ERROR: Invalid url http://www.abc.net.au/tv/qanda/mp-profiles/park.htm for division parkes
ERROR: Invalid url http://www.abc.net.au/tv/qanda/mp-profiles/gilm.htm for division gilmore
ERROR: Invalid url http://www.abc.net.au/tv/qanda/mp-profiles/ryan.htm for division ryan
ERROR: Invalid url http://www.abc.net.au/tv/qanda/mp-profiles/curt.htm for division curtin
ERROR: Invalid url http://www.abc.net.au/tv/qanda/mp-profiles/newc.htm for division newcastle
ERROR: Invalid url http://www.abc.net.au/tv/qanda/mp-profiles/cori.htm for division corio
ERROR: Invalid url http://www.abc.net.au/tv/qanda/mp-profiles/went.htm for division wentworth
ERROR: Invalid url http://www.abc.net.au/tv/qanda/mp-profiles/wats.htm for division watson
ERROR: Invalid url http://www.abc.net.au/tv/qanda/mp-profiles/wann.htm for division wannon
ERROR: Invalid url http://www.abc.net.au/tv/qanda/mp-profiles/brad.htm for division braddon
ERROR: Invalid url http://www.abc.net.au/tv/qanda/mp-profiles/isaa.htm for division isaacs
ERROR: Invalid url http://www.abc.net.au/tv/qanda/mp-profiles/indi.htm for division indi
ERROR: Invalid url http://www.abc.net.au/tv/qanda/mp-profiles/fowl.htm for division fowler
ERROR: Invalid url http://www.abc.net.au/tv/qanda/mp-profiles/grif.htm for division griffith
ERROR: Invalid url http://www.abc.net.au/tv/qanda/mp-profiles/hind.htm for division hindmarsh
ERROR: Invalid url http://www.abc.net.au/tv/qanda/mp-profiles/rank.htm for division rankin
ERROR: Invalid url http://www.abc.net.au/tv/qanda/mp-profiles/rich.htm for division richmond
ERROR: Invalid url http://www.abc.net.au/tv/qanda/mp-profiles/gort.htm for division gorton
ERROR: Invalid url http://www.abc.net.au/tv/qanda/mp-profiles/gipp.htm for division gippsland
ERROR: Invalid url http://www.abc.net.au/tv/qanda/mp-profiles/brfd.htm for division bradfield
ERROR: Invalid url http://www.abc.net.au/tv/qanda/mp-profiles/gell.htm for division gellibrand
ERROR: Invalid url http://www.abc.net.au/tv/qanda/mp-profiles/dura.htm for division durack
ERROR: Invalid url http://www.abc.net.au/tv/qanda/mp-profiles/lill.htm for division lilley
ERROR: Invalid url http://www.abc.net.au/tv/qanda/mp-profiles/ocon.htm for division o'connor
ERROR: Invalid url http://www.abc.net.au/tv/qanda/mp-profiles/wbay.htm for division wide bay
ERROR: Invalid url http://www.abc.net.au/tv/qanda/mp-profiles/thro.htm for division throsby
ERROR: Invalid url http://www.abc.net.au/tv/qanda/mp-profiles/scul.htm for division scullin
ERROR: Invalid url http://www.abc.net.au/tv/qanda/mp-profiles/mcph.htm for division mcpherson
ERROR: Invalid url http://www.abc.net.au/tv/qanda/mp-profiles/kooy.htm for division kooyong
ERROR: Invalid url http://www.abc.net.au/tv/qanda/mp-profiles/kenn.htm for division kennedy
ERROR: Invalid url http://www.abc.net.au/tv/qanda/mp-profiles/cowa.htm for division cowan
ERROR: Invalid url http://www.abc.net.au/tv/qanda/mp-profiles/flyn.htm for division flynn
ERROR: Invalid url http://www.abc.net.au/tv/qanda/mp-profiles/nsyd.htm for division north sydney
ERROR: Invalid url http://www.abc.net.au/tv/qanda/mp-profiles/mcew.htm for division mcewen
ERROR: Invalid url http://www.abc.net.au/tv/qanda/mp-profiles/warr.htm for division warringah
ERROR: Invalid url http://www.abc.net.au/tv/qanda/mp-profiles/mcmi.htm for division mcmillan
ERROR: Invalid url http://www.abc.net.au/tv/qanda/mp-profiles/mari.htm for division maribyrnong
ERROR: Invalid url http://www.abc.net.au/tv/qanda/mp-profiles/neng.htm for division new england
ERROR: Invalid url http://www.abc.net.au/tv/qanda/mp-profiles/monc.htm for division moncrieff
ERROR: Invalid url http://www.abc.net.au/tv/qanda/mp-profiles/macq.htm for division macquarie
ERROR: Invalid url http://www.abc.net.au/tv/qanda/mp-profiles/fish.htm for division fisher
ERROR: Invalid url http://www.abc.net.au/tv/qanda/mp-profiles/chif.htm for division chifley
ERROR: Invalid url http://www.abc.net.au/tv/qanda/mp-profiles/more.htm for division moreton
ERROR: Invalid url http://www.abc.net.au/tv/qanda/mp-profiles/emon.htm for division eden-monaro
ERROR: Invalid url http://www.abc.net.au/tv/qanda/mp-profiles/daws.htm for division dawson
ERROR: Invalid url http://www.abc.net.au/tv/qanda/mp-profiles/parr.htm for division parramatta
ERROR: Invalid url http://www.abc.net.au/tv/qanda/mp-profiles/bris.htm for division brisbane
ERROR: Invalid url http://www.abc.net.au/tv/qanda/mp-profiles/groo.htm for division groom
ERROR: Invalid url http://www.abc.net.au/tv/qanda/mp-profiles/pate.htm for division paterson
ERROR: Invalid url http://www.abc.net.au/tv/qanda/mp-profiles/melb.htm for division melbourne
ERROR: Invalid url http://www.abc.net.au/tv/qanda/mp-profiles/char.htm for division charlton
ERROR: Invalid url http://www.abc.net.au/tv/qanda/mp-profiles/cunn.htm for division cunningham
ERROR: Invalid url http://www.abc.net.au/tv/qanda/mp-profiles/grey.htm for division grey
ERROR: Invalid url http://www.abc.net.au/tv/qanda/mp-profiles/page.htm for division page
ERROR: Invalid url http://www.abc.net.au/tv/qanda/mp-profiles/will.htm for division wills
ERROR: Invalid url http://www.abc.net.au/tv/qanda/mp-profiles/cook.htm for division cook
ERROR: Invalid url http://www.abc.net.au/tv/qanda/mp-profiles/holt.htm for division holt
ERROR: Invalid url http://www.abc.net.au/tv/qanda/mp-profiles/fran.htm for division franklin
ERROR: Invalid url http://www.abc.net.au/tv/qanda/mp-profiles/lyne.htm for division lyne
ERROR: Invalid url http://www.abc.net.au/tv/qanda/mp-profiles/murr.htm for division murray
ERROR: Invalid url http://www.abc.net.au/tv/qanda/mp-profiles/calw.htm for division calwell
ERROR: Invalid url http://www.abc.net.au/tv/qanda/mp-profiles/pear.htm for division pearce
ERROR: Invalid url http://www.abc.net.au/tv/qanda/mp-profiles/pade.htm for division port adelaide
ERROR: Invalid url http://www.abc.net.au/tv/qanda/mp-profiles/lyon.htm for division lyons
ERROR: Invalid url http://www.abc.net.au/tv/qanda/mp-profiles/cowp.htm for division cowper
ERROR: Invalid url http://www.abc.net.au/tv/qanda/mp-profiles/bruc.htm for division bruce
ERROR: Invalid url http://www.abc.net.au/tv/qanda/mp-profiles/frem.htm for division fremantle
ERROR: Invalid url http://www.abc.net.au/tv/qanda/mp-profiles/hunt.htm for division hunter
ERROR: Invalid url http://www.abc.net.au/tv/qanda/mp-profiles/canb.htm for division canberra
ERROR: Invalid url http://www.abc.net.au/tv/qanda/mp-profiles/flin.htm for division flinders
ERROR: Invalid url http://www.abc.net.au/tv/qanda/mp-profiles/leic.htm for division leichhardt
ERROR: Invalid url http://www.abc.net.au/tv/qanda/mp-profiles/fadd.htm for division fadden
ERROR: Invalid url http://www.abc.net.au/tv/qanda/mp-profiles/tang.htm for division tangney
ERROR: Invalid url http://www.abc.net.au/tv/qanda/mp-profiles/shor.htm for division shortland
ERROR: Invalid url http://www.abc.net.au/tv/qanda/mp-profiles/fair.htm for division fairfax
ERROR: Invalid url http://www.abc.net.au/tv/qanda/mp-profiles/maca.htm for division macarthur
ERROR: Invalid url http://www.abc.net.au/tv/qanda/mp-profiles/dunk.htm for division dunkley
ERROR: Invalid url http://www.abc.net.au/tv/qanda/mp-profiles/ford.htm for division forde
ERROR: Invalid url http://www.abc.net.au/tv/qanda/mp-profiles/werr.htm for division werriwa
ERROR: Invalid url http://www.abc.net.au/tv/qanda/mp-profiles/mall.htm for division mallee
ERROR: Invalid url http://www.abc.net.au/tv/qanda/mp-profiles/mpor.htm for division melbourne ports
ERROR: Invalid url http://www.abc.net.au/tv/qanda/mp-profiles/wake.htm for division wakefield
ERROR: Invalid url http://www.abc.net.au/tv/qanda/mp-profiles/reid.htm for division reid
ERROR: Invalid url http://www.abc.net.au/tv/qanda/mp-profiles/case.htm for division casey
ERROR: Invalid url http://www.abc.net.au/tv/qanda/mp-profiles/menz.htm for division menzies
ERROR: Invalid url http://www.abc.net.au/tv/qanda/mp-profiles/gold.htm for division goldstein
ERROR: Invalid url http://www.abc.net.au/tv/qanda/mp-profiles/king.htm for division kingston
ERROR: Invalid url http://www.abc.net.au/tv/qanda/mp-profiles/lind.htm for division lindsay
ERROR: Couldn't lookup division Warringah
ERROR: Couldn't lookup division Grayndler
ERROR: Couldn't lookup division Menzies
ERROR: Couldn't lookup division Cunningham
ERROR: Couldn't lookup division Curtin
ERROR: Couldn't lookup division McMahon
ERROR: Couldn't lookup division McMillan
ERROR: Couldn't lookup division Watson
ERROR: Couldn't lookup division Port Adelaide
ERROR: Couldn't lookup division Holt
ERROR: Couldn't lookup division Wakefield
ERROR: Couldn't lookup division Moncrieff
ERROR: Couldn't lookup division Blaxland
ERROR: Couldn't lookup division Franklin
ERROR: Couldn't lookup division Parkes
ERROR: Couldn't lookup division Melbourne Ports
ERROR: Couldn't lookup division Isaacs
ERROR: Couldn't lookup division Dickson
ERROR: Couldn't lookup division Richmond
ERROR: Couldn't lookup division Adelaide
ERROR: Couldn't lookup division Leichhardt
ERROR: Couldn't lookup division Hunter
ERROR: Couldn't lookup division Hindmarsh
ERROR: Couldn't lookup division Cowper
ERROR: Couldn't lookup division Mitchell
ERROR: Couldn't lookup division Fowler
ERROR: Couldn't lookup division Flinders
ERROR: Couldn't lookup division Swan
ERROR: Couldn't lookup division New England
ERROR: Couldn't lookup division Kennedy
ERROR: Couldn't lookup division Stirling
ERROR: Couldn't lookup division Eden-Monaro
ERROR: Couldn't lookup division Ballarat
ERROR: Couldn't lookup division Bowman
ERROR: Couldn't lookup division Farrer
ERROR: Couldn't lookup division Jagajaga
ERROR: Couldn't lookup division Forrest
ERROR: Couldn't lookup division Corio
ERROR: Couldn't lookup division Cook
ERROR: Couldn't lookup division Blair
ERROR: Couldn't lookup division Gorton
ERROR: Couldn't lookup division Parramatta
ERROR: Couldn't lookup division Moreton
ERROR: Couldn't lookup division Sydney
ERROR: Couldn't lookup division Sturt
ERROR: Couldn't lookup division Grey
ERROR: Couldn't lookup division Kingston
ERROR: Couldn't lookup division Fadden
ERROR: Couldn't lookup division Maribyrnong
ERROR: Couldn't lookup division Casey
ERROR: Couldn't lookup division Lingiari
ERROR: Couldn't lookup division Lilley
ERROR: Couldn't lookup division Wentworth
ERROR: Couldn't lookup division Calwell
ERROR: Couldn't lookup division Bonner
ERROR: Couldn't lookup division La Trobe
ERROR: Couldn't lookup division Makin
ERROR: Couldn't lookup division Gippsland
ERROR: Couldn't lookup division Batman
ERROR: Couldn't lookup division Bradfield
ERROR: Couldn't lookup division Higgins
ERROR: Couldn't lookup division Bennelong
ERROR: Couldn't lookup division Dawson
ERROR: Couldn't lookup division Denison
ERROR: Couldn't lookup division Flynn
ERROR: Couldn't lookup division Forde
ERROR: Couldn't lookup division Hasluck
ERROR: Couldn't lookup division McEwen
ERROR: Couldn't lookup division Melbourne
ERROR: Couldn't lookup division Canberra
ERROR: Couldn't lookup division Whitlam
ERROR: Couldn't lookup division Kooyong
ERROR: Couldn't lookup division Wannon
ERROR: Couldn't lookup division Riverina
ERROR: Couldn't lookup division McPherson
ERROR: Couldn't lookup division Fenner
ERROR: Couldn't lookup division Aston
ERROR: Couldn't lookup division Chifley
ERROR: Couldn't lookup division Hughes
ERROR: Couldn't lookup division Greenway
ERROR: Couldn't lookup division Wright
ERROR: Couldn't lookup division Ryan
ERROR: Couldn't lookup division Kingsford Smith
ERROR: Couldn't lookup division Banks
ERROR: Couldn't lookup division Barker
ERROR: Couldn't lookup division Bendigo
ERROR: Couldn't lookup division Capricornia
ERROR: Couldn't lookup division Corangamite
ERROR: Couldn't lookup division Deakin
ERROR: Couldn't lookup division Gellibrand
ERROR: Couldn't lookup division Gilmore
ERROR: Couldn't lookup division Hinkler
ERROR: Couldn't lookup division Indi
ERROR: Couldn't lookup division Lalor
ER/usr/lib/ruby/gems/1.8/gems/mechanize-0.9.2/lib/www/mechanize.rb:546:in `fetch_page': 404 => Net::HTTPNotFound (WWW::Mechanize::ResponseCodeError)
        from /usr/lib/ruby/gems/1.8/gems/mechanize-0.9.2/lib/www/mechanize.rb:229:in `get'
        from ../../openaustralia-parser/parse-member-links.rb:186
ROR: Couldn't lookup division Lyne
ERROR: Couldn't lookup division Mallee
ERROR: Couldn't lookup division Moore
ERROR: Couldn't lookup division Newcastle
ERROR: Couldn't lookup division Page
ERROR: Couldn't lookup division Petrie
ERROR: Couldn't lookup division Rankin
ERROR: Couldn't lookup division Reid
ERROR: Couldn't lookup division Robertson
ERROR: Couldn't lookup division Scullin
ERROR: Couldn't lookup division Shortland
ERROR: Couldn't lookup division Hotham
ERROR: Couldn't lookup division Pearce
ERROR: Couldn't lookup division O'Connor
ERROR: Couldn't lookup division Hume
ERROR: Couldn't lookup division Durack
ERROR: Couldn't lookup division Griffith
ERROR: Couldn't lookup division Canning
ERROR: Couldn't lookup division North Sydney
ERROR: Couldn't lookup division Barton
ERROR: Couldn't lookup division Bass
ERROR: Couldn't lookup division Braddon
ERROR: Couldn't lookup division Burt
ERROR: Couldn't lookup division Chisholm
ERROR: Couldn't lookup division Cowan
ERROR: Couldn't lookup division Dobell
ERROR: Couldn't lookup division Fairfax
ERROR: Couldn't lookup division Herbert
ERROR: Couldn't lookup division Lindsay
ERROR: Couldn't lookup division Longman
ERROR: Couldn't lookup division Lyons
ERROR: Couldn't lookup division Macarthur
ERROR: Couldn't lookup division Macquarie
ERROR: Couldn't lookup division Mayo
ERROR: Couldn't lookup division Murray
ERROR: Couldn't lookup division Paterson
ERROR: Couldn't lookup division Solomon
ERROR: Couldn't lookup division Mackellar
ERROR: Couldn't lookup division Dunkley
ERROR: Couldn't lookup division Oxley
ERROR: Couldn't lookup division Brisbane
ERROR: Couldn't lookup division Boothby
ERROR: Couldn't lookup division Calare
ERROR: Couldn't lookup division Brand
ERROR: Couldn't lookup division Bruce
ERROR: Couldn't lookup division Tangney
ERROR: Couldn't lookup division Wills
ERROR: Couldn't lookup division Berowra
ERROR: Couldn't lookup division Groom
ERROR: Couldn't lookup division Maranoa
ERROR: Couldn't lookup division Perth
ERROR: Couldn't lookup division Wide Bay
ERROR: Couldn't lookup division Fremantle
ERROR: Couldn't lookup division Goldstein
ERROR: Couldn't lookup division Werriwa
ERROR: Couldn't lookup division Fisher
WARNING: Can't find Senator Judith Adams
WARNING: Can't find Senator Mark Arbib
WARNING: Can't find Senator Mark Bishop
WARNING: Can't find Senator Ronald Boswell
WARNING: Can't find Senator Sue Boyce
WARNING: Can't find Senator Bob Brown
WARNING: Can't find Senator Richard Colbeck
WARNING: Can't find Senator Helen Coonan
WARNING: Can't find Senator Trish Crossin
WARNING: Can't find Senator Sean Edwards
WARNING: Can't find Senator Alan Eggleston
WARNING: Can't find Senator Christopher Evans
WARNING: Can't find Senator John Faulkner
WARNING: Can't find Senator David Feeney
WARNING: Can't find Senator Mary Jo Fisher
WARNING: Can't find Senator Mark Furner
WARNING: Can't find Senator Bill Heffernan
WARNING: Can't find Senator John Hogg
WARNING: Can't find Senator Gary Humphries
WARNING: Can't find Senator David Johnston
WARNING: Can't find Senator Barnaby Joyce
WARNING: Can't find Senator Helen Kroger
WARNING: Can't find Senator Joe Ludwig
WARNING: Can't find Senator Kate Lundy
WARNING: Can't find Senator John Madigan
WARNING: Can't find Senator Brett Mason
WARNING: Can't find Senator Anne McEwen
WARNING: Can't find Senator Jan McLucas
WARNING: Can't find Senator Christine Milne
WARNING: Can't find Senator Michael Ronaldson
WARNING: Can't find Senator Nick Sherry
WARNING: Can't find Senator Ursula Stephens
WARNING: Can't find Senator Matt Thistlethwaite
WARNING: Can't find Senator Penny Wright
Register of interests from APH...
https://theyvoteforyou.org.au/feeds/mp-info.xml?house=representatives Can't connect to theyvoteforyou.org.au:443 (certificate verify failed) at ./mpinfoin.pl line 105

no element found at line 1, column 0, byte 0 at /usr/lib/perl5/XML/Parser.pm line 187
 at ./mpinfoin.pl line 105
```

#599 is related.

**Comment by henare** [comment]
I've noted #606 - it has to be fixed by the ABC. We're doing the right thing and not showing broken links.

I've fixed #607.

So all we need to do is fix:

```
https://theyvoteforyou.org.au/feeds/mp-info.xml?house=representatives Can't connect to theyvoteforyou.org.au:443 (certificate verify failed) at ./mpinfoin.pl line 105

no element found at line 1, column 0, byte 0 at /usr/lib/perl5/XML/Parser.pm line 187
 at ./mpinfoin.pl line 105
```

It doesn't happen locally and didn't always happen so something on the server has changed. It was probably a Perl update. Joy.
