### ISSUE TITLE
2016-09-15 not loaded

### ISSUE THREAD

**Issue by equivalentideas** [openaustralia/openaustralia#610]
See http://www.openaustralia.org.au/debates/?y=2016

Parliament was sitting but nothing loaded.

Here's the error from the cron email:

```
Start time: 2016-09-16 09:05:02 AEST
Parsing from APH to XML and loading into the database
[DEPRECATION] requiring "RMagick" is deprecated. Use "rmagick" instead
WARNING: Nokogiri was built against LibXML version 2.7.6, but has dynamically loaded 2.7.8


parse-speeche:   0% |                                          | ETA:  --:--:--
parse-speeche:  50% |ooooooooooooooooooooo                     | ETA:  00:00:13
./../openaustralia-parser/lib/hansard_speech.rb:277:in `throw': uncaught throw `Unexpected tag insertmotion' (NameError)
        from ../../openaustralia-parser/lib/hansard_speech.rb:277:in `clean_content_any'
        from ../../openaustralia-parser/lib/hansard_speech.rb:135:in `clean_content_para_content'
        from ../../openaustralia-parser/lib/hansard_speech.rb:133:in `each'
        from ../../openaustralia-parser/lib/hansard_speech.rb:133:in `clean_content_para_content'
        from ../../openaustralia-parser/lib/hansard_speech.rb:162:in `clean_content_para'
        from ../../openaustralia-parser/lib/hansard_speech.rb:251:in `clean_content_any'
        from ../../openaustralia-parser/lib/hansard_speech.rb:284:in `clean_content_recurse'
        from ../../openaustralia-parser/lib/hpricot_additions.rb:7:in `each_child_node'
        from ../../openaustralia-parser/lib/hpricot_additions.rb:7:in `each'
        from ../../openaustralia-parser/lib/hpricot_additions.rb:7:in `each_child_node'
        from ../../openaustralia-parser/lib/hansard_speech.rb:283:in `clean_content_recurse'
        from ../../openaustralia-parser/lib/hansard_speech.rb:245:in `clean_content_any'
        from ../../openaustralia-parser/lib/hansard_speech.rb:290:in `clean_content'
        from ../../openaustralia-parser/lib/hansard_parser.rb:178:in `parse_date_house'
        from ../../openaustralia-parser/lib/hansard_parser.rb:170:in `each'
        from ../../openaustralia-parser/lib/hansard_parser.rb:170:in `parse_date_house'
        from ../../openaustralia-parser/lib/hansard_parser.rb:159:in `each'
        from ../../openaustralia-parser/lib/hansard_parser.rb:159:in `parse_date_house'
        from ../../openaustralia-parser/parse-speeches.rb:94
Xapian indexing
Running rssgenerate
./sitemap.rb:386:in `notify_search_engines': uninitialized constant Sitemap::PINGMYMAP_API_URL (NameError)
        from ./sitemap.rb:453
Writing sitemap file (/srv/www/www.openaustralia.org/current/twfy/www/docs/sitemaps/sitemap1.xml.gz)...
Writing sitemap file (/srv/www/www.openaustralia.org/current/twfy/www/docs/sitemaps/sitemap2.xml.gz)...
Writing sitemap file (/srv/www/www.openaustralia.org/current/twfy/www/docs/sitemaps/sitemap3.xml.gz)...
Writing sitemap file (/srv/www/www.openaustralia.org/current/twfy/www/docs/sitemaps/sitemap4.xml.gz)...
Writing sitemap file (/srv/www/www.openaustralia.org/current/twfy/www/docs/sitemaps/sitemap5.xml.gz)...
Writing sitemap file (/srv/www/www.openaustralia.org/current/twfy/www/docs/sitemaps/sitemap6.xml.gz)...
Writing sitemap file (/srv/www/www.openaustralia.org/current/twfy/www/docs/sitemaps/sitemap7.xml.gz)...
Writing sitemap file (/srv/www/www.openaustralia.org/current/twfy/www/docs/sitemaps/sitemap8.xml.gz)...
Writing sitemap file (/srv/www/www.openaustralia.org/current/twfy/www/docs/sitemaps/sitemap9.xml.gz)...
Writing sitemap file (/srv/www/www.openaustralia.org/current/twfy/www/docs/sitemaps/sitemap10.xml.gz)...
Whole thing done time: 2016-09-16 10:27:34
```

**Comment by equivalentideas** [comment]
I've done a search of the xml files for that day:

* [House](http://parlinfo.aph.gov.au/parlInfo/download/chamber/hansardr/9de5f081-9ccf-4f72-a05a-02462c1f3a0c/toc_unixml/House%20of%20Representatives_2016_09_15_4439.xml;fileType=text%2Fxml)
* [Senate](http://parlinfo.aph.gov.au/parlInfo/download/chamber/hansards/12ffc4fc-3b68-4c54-ae4d-646b285b8ae8/toc_unixml/Senate_2016_09_15_4438.xml;fileType=text%2Fxml)

I can't find a mention of that the tag `insertmotion` that’s raising this error:

```
./../openaustralia-parser/lib/hansard_speech.rb:277:in `throw': uncaught throw `Unexpected tag insertmotion' (NameError)
```

So maybe this has been cleaned up. I'm now going to try running the parser locally to see if it still fails.

**Comment by equivalentideas** [comment]
This runs find locally, so I'm assuming that whatever problem there was has been fixed.

**Comment by equivalentideas** [comment]
## steps to fixing this on Production

* [ ] trash html cache
* [ ] run parse-speeches with just the date
* [ ] then I'll see it on the site
* [ ] run indexing
* [ ] if we don't want email alerts sent for this loaded data then follow [these steps](https://github.com/openaustralia/openaustralia/wiki/Email-alert-tasks#skipping-email-alerts) (because this is recent data we're happy for it to go out).

**Comment by equivalentideas** [comment]
This is fixed now http://www.openaustralia.org.au/debates/?d=2016-09-15

**Comment by equivalentideas** [comment]
Thanks for your help @henare ;-)

**Comment by henare** [comment]
Great work finding and fixing this @equivalentideas :neckbeard:
