### ISSUE TITLE
2017-06-22 debates missing

### ISSUE THREAD

**Issue by wwwalker** [openaustralia/openaustralia#623]
At http://www.openaustralia.org.au/hansard/ there is only up to 21/6/17 debates not 22/6/17.

There is a Telecommunications (Regional Broadband Scheme) Charge Bill 2017 due on 22/6/17 I cannot find.

Is 22/6/17 being loaded still?

**Comment by henare** [comment]
@wwwalker thanks for reporting this :+1: it looks like a problem parsing that day. Here's the log from that day's cronjob:

```Start time: 2017-06-23 09:05:01 AEST
Parsing from APH to XML and loading into the database
[DEPRECATION] requiring "RMagick" is deprecated. Use "rmagick" instead
WARNING: Nokogiri was built against LibXML version 2.7.6, but has dynamically loaded 2.7.8


parse-speeche:   0% |                                          | ETA:  --:--:--
./../openaustralia-parser/lib/hansard_speech.rb:277:in `throw': uncaught throw `Unexpected tag hh:mm' (NameError)
        from ../../openaustralia-parser/lib/hansard_speech.rb:277:in `clean_content_any'
        from ../../openaustralia-parser/lib/hansard_speech.rb:135:in `clean_content_para_content'
        from ../../openaustralia-parser/lib/hansard_speech.rb:133:in `each'
        from ../../openaustralia-parser/lib/hansard_speech.rb:133:in `clean_content_para_content'
        from ../../openaustralia-parser/lib/hansard_speech.rb:160:in `clean_content_para'
        from ../../openaustralia-parser/lib/hansard_speech.rb:251:in `clean_content_any'
        from ../../openaustralia-parser/lib/hansard_speech.rb:284:in `clean_content_recurse'
        from ../../openaustralia-parser/lib/hpricot_additions.rb:7:in `each_child_node'
        from ../../openaustralia-parser/lib/hpricot_additions.rb:7:in `each'
        from ../../openaustralia-parser/lib/hpricot_additions.rb:7:in `each_child_node'
        from ../../openaustralia-parser/lib/hansard_speech.rb:283:in `clean_content_recurse'
        from ../../openaustralia-parser/lib/hansard_speech.rb:247:in `clean_content_any'
        from ../../openaustralia-parser/lib/hansard_speech.rb:290:in `clean_content'
        from ../../openaustralia-parser/lib/hansard_parser.rb:178:in `parse_date_house'
        from ../../openaustralia-parser/lib/hansard_parser.rb:170:in `each'
        from ../../openaustralia-parser/lib/hansard_parser.rb:170:in `parse_date_house'
        from ../../openaustralia-parser/lib/hansard_parser.rb:159:in `each'
        from ../../openaustralia-parser/lib/hansard_parser.rb:159:in `parse_date_house'
        from ../../openaustralia-parser/parse-speeches.rb:88
Xapian indexing
xapian indexing lords 2017-06-21

Running rssgenerate
./sitemap.rb:386:in `notify_search_engines': uninitialized constant Sitemap::PINGMYMAP_API_URL (NameError)
        from ./sitemap.rb:453
Writing sitemap file (/srv/www/www.openaustralia.org/current/twfy/www/docs/sitemaps/sitemap1.xml.gz)...
Writing sitemap file (/srv/www/www.openaustralia.org/current/twfy/www/docs/sitemaps/sitemap2.xml.gz)...
Writing sitemap file (/srv/www/www.openaustralia.org/current/twfy/www/docs/sitemaps/sitemap3.xml.gz)...
Writing sitemap file (/srv/www/www.openaustralia.org/current/twfy/www/docs/sitemaps/sitemap4.xml.gz)...
Writing sitemap file (/srv/www/www.openaustralia.org/current/twfy/www/docs/sitemaps/sitemap5.xml.gz)...
Writing sitemap file (/srv/www/www.openaustralia.org/current/twfy/www/docs/sitemaps/sitemap6.xml.gz)...
Writing sitemap file (/srv/www/www.openaustralia.org/current/twfy/www/docs/sitemaps/sitemap7.xml.gz)...
Writing sitemap file (/srv/www/www.openaustralia.org/current/twfy/www/docs/sitemaps/sitemap8.xml.gz)...
Writing sitemap file (/srv/www/www.openaustralia.org/current/twfy/www/docs/sitemaps/sitemap9.xml.gz)...
Writing sitemap file (/srv/www/www.openaustralia.org/current/twfy/www/docs/sitemaps/sitemap10.xml.gz)...
Writing sitemap file (/srv/www/www.openaustralia.org/current/twfy/www/docs/sitemaps/sitemap11.xml.gz)...
Whole thing done time: 2017-06-23 10:38:12
```

**Comment by henare** [comment]
>At http://www.openaustralia.org.au/hansard/ there is only up to 21/6/17 debates not 22/6/17.

You can also see another missing day in the little calendar there too:

![selection_001](https://user-images.githubusercontent.com/48945/28451274-abb53b78-6e2f-11e7-8c5a-bd47cf978604.png)

Logged as #624.

Thanks for helping find these problems @wwwalker :star2:

**Comment by henare** [comment]
Deleted cache, ran parser again, fixed.
