### ISSUE TITLE
Need absolute URL downloading image for Robert Francis Ray

### ISSUE THREAD

**Issue by jamezpolley** [openaustralia/openaustralia#634]
```
Found biography page for Robert Francis Ray
/usr/local/rvm/gems/ruby-1.8.7-p374/gems/mechanize-0.9.2/lib/www/mechanize/chain/uri_resolver.rb:49:in `handle': need absolute URL (RuntimeError)
        from /usr/local/rvm/gems/ruby-1.8.7-p374/gems/mechanize-0.9.2/lib/www/mechanize/chain.rb:25:in `handle'
        from /usr/local/rvm/gems/ruby-1.8.7-p374/gems/mechanize-0.9.2/lib/www/mechanize.rb:445:in `fetch_page'
        from /usr/local/rvm/gems/ruby-1.8.7-p374/gems/mechanize-0.9.2/lib/www/mechanize.rb:229:in `get'
        from /srv/www/openaustralia/openaustralia-parser/lib/mechanize_proxy.rb:136:in `get'
        from /srv/www/openaustralia/openaustralia-parser/lib/mechanize_proxy.rb:21:in `load_and_cache_page'
        from /srv/www/openaustralia/openaustralia-parser/lib/mechanize_proxy.rb:136:in `get'
        from /srv/www/openaustralia/openaustralia-parser/lib/people_image_downloader.rb:153:in `extract_image'
        from /srv/www/openaustralia/openaustralia-parser/lib/people_image_downloader.rb:30:in `download'
        from /srv/www/openaustralia/openaustralia-parser/lib/people_image_downloader.rb:27:in `each'
        from /srv/www/openaustralia/openaustralia-parser/lib/people_image_downloader.rb:27:in `download'
        from /srv/www/openaustralia/openaustralia-parser/lib/people.rb:180:in `download_images'
        from /srv/www/openaustralia/openaustralia-parser/member-images.rb:12
```

```
[james@blister:~/src/oaf/openaustralia] [oafansible25] master(+4/-4,2) ± git submodule status
+fa933e251dc821d0ec517d72de13ae9fe384b7de openaustralia-parser (heads/master)
 ed6e800bbdcacbee41ae04b0bd1c8e57fea6e9ae perllib (heads/master)
 802a25b1831d5ba9e0c8f8c859ddf8180d9d70c1 phplib (heads/master)
 3637160670eebbb9375e0f35770ce251d1b61014 rblib (heads/master)
 f7ac05c48a70ab6bcc7dc425a924fcb296343bd3 shlib (heads/master)
 b773b1926dbe723ac9753c5af66a0b0cb1d87d58 twfy (heads/master)
```

this repo is at d5a75c5

**Comment by jamezpolley** [comment]
This seems to have been related to bad cache data. On a subsequent test, the parser died while parsing one particular page, runs after that exhibited this same error on that page. Removing that page from the cache meant the parser could continue.
