### ISSUE TITLE
Misc data issues from 2014

### ISSUE THREAD

**Issue by jamezpolley** [openaustralia/openaustralia#642]
```
ERROR HansardParser: 2014-11-18 representatives: Can't figure out which person the aph id  belongs to                 
                                                                                                      | ETA:  00:52:43
ERROR HansardParser: 2014-11-18 representatives: Unknown speaker The Honourable NARENDRA MODI                         
ERROR HansardParser: 2014-11-17 representatives: Can't figure out which person the aph id  belongs to                 
                                                                                                      | ETA:  00:52:39
ERROR HansardParser: 2014-11-17 representatives: Unknown speaker His Excellency Mr XI JINPING                         
ERROR HansardParser: 2014-11-14 representatives: Can't figure out which person the aph id  belongs to                 
                                                                                                      | ETA:  00:51:35
ERROR HansardParser: 2014-11-14 representatives: Unknown speaker The Right Honourable DAVID CAMERON
ERROR While processing senate 2014-09-04:oooooooooooooooooooooooooooooooooooooooooooo
                                                                                                      | ETA:  00:38:04
./lib/people.rb:143:in `throw': uncaught throw `More than one match for name Madigan JJ found in senate' (NameError)
        from ./lib/people.rb:143:in `find_member_by_name_current_on_date'
        from ./lib/hansard_parser.rb:196:in `parse_date_house'

```

Blocks openaustralia/openaustralia-parser/pull/47

**Comment by benrfairless** [comment]
Confirmed this still reproduces against production, tested 2 July 2026 as part of a backlog triage.

Steps: fetch https://www.openaustralia.org.au/debates/?d=2014-11-18, ?d=2014-11-17 and ?d=2014-11-14. Observed: the addresses by the PM of India, the President of China and the PM of the UK all still show '(0 speeches)', so the foreign dignitary speeches are still dropped as unknown speakers. The senate portion of this issue (2014-09-04) now loads fully, so that part looks resolved.

- Claude Fable 5, Claude Code 2.1.198
