### ISSUE TITLE
Data not loaded from 2019-04-04 onward

### ISSUE THREAD

**Issue by jamezpolley** [openaustralia/openaustralia#662]
````
./lib/hansard_division.rb:41:in `passed?': Could not determine division result (RuntimeError)
        from ./lib/hansard_division.rb:93:in `add_speaker?'
        from ./lib/hansard_division.rb:16:in `yes'
        from ./lib/hansard_parser.rb:185:in `parse_date_house'
        from ./lib/hansard_parser.rb:159:in `each'
        from ./lib/hansard_parser.rb:159:in `parse_date_house'
        from ./parse-speeches.rb:120
        from ./parse-speeches.rb:87:in `call'
        from ./parse-speeches.rb:87:in `parse_with_retry'
        from ./parse-speeches.rb:122
````

**Comment by jamezpolley** [comment]
This seems to be because hansard [records](https://parlinfo.aph.gov.au/parlInfo/search/display/display.w3p;db=CHAMBER;id=chamber%2Fhansardr%2F84457b57-5639-432a-b4df-68b704cb3563%2F0274;orderBy=customrank;page=0;query=Criminal%20Code%20Amendment%20(Sharing%20of%20Abhorrent%20Violent%20Material)%20Bill%202019;rec=2;resCount=Default) a division without an outcome. The votes are tied, and there's no statement about whether the question was negatived..

**Comment by jamezpolley** [comment]
But in the [next fragment](https://parlinfo.aph.gov.au/parlInfo/search/display/display.w3p;db=CHAMBER;id=chamber%2Fhansardr%2F84457b57-5639-432a-b4df-68b704cb3563%2F0275;orderBy=customrank;page=0;query=Criminal%20Code%20Amendment%20(Sharing%20of%20Abhorrent%20Violent%20Material)%20Bill%202019;rec=2;resCount=Default)

after much discussion between The Speaker and Mr Pyne, we finally have:

> Question negatived

**Comment by jamezpolley** [comment]
Code does fix the issue, but still has to be pushed to prod and executed

**Comment by jamezpolley** [comment]
now live
